# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
secure_input_notification: false
enable_passive: false
toggle_key: OFF
matches:
  - trigger: "Rene "
    replace: "RenÃ©"
  - trigger: "Zoe"
    replace: "ZoÃ«"
  - trigger: ":rene"
    replace: "RenÃ©"
  - trigger: ":zoom:"
    replace: "https://whereby.com/sethmesser"
  - trigger: ":meet:"
    replace: "https://whereby.com/sethmesser"
  - trigger: ":tm:"
    replace: "â„¢"
  - trigger: ":shrug:"
    replace: "Â¯\\_(ãƒ„)_/Â¯"
  - trigger: ":nope:"
    replace: "à² _à² "
  - trigger: ":heart:"
    replace: "â¤ï¸"
  - trigger: ":point:"
    replace: "ğŸ‘†"
  - trigger: ":pointup:"
    replace: "ğŸ‘†"
  - trigger: ":knuckles:"
    replace: "ğŸ‘Š"
  - trigger: ":fist:"
    replace: "âœŠ"
  - trigger: ":wave:"
    replace: "ğŸ‘‹"
  - trigger: ":thumb:"
    replace: "ğŸ‘"
  - trigger: ":+1:"
    replace: "ğŸ‘"
  - trigger: ":thumbsup:"
    replace: "ğŸ‘"
  - trigger: ":-1:"
    replace: "ğŸ‘"
  - trigger: ":thumbsdown:"
    replace: "ğŸ‘"
  - trigger: ":flex:"
    replace: "ğŸ’ª"
  - trigger: ":pray:"
    replace: "ğŸ™"
  - trigger: ":rock:"
    replace: "ğŸ¤˜"
  - trigger: ":rofl:"
    replace: "ğŸ¤£"
  - trigger: ":poop:"
    replace: "ğŸ’©"
  - trigger: ":100:"
    replace: "ğŸ’¯"
  - trigger: ":eyes:"
    replace: "ğŸ‘€"
  - trigger: ":facepalm:"
    replace: "ğŸ¤¦"
  - trigger: ":hands:"
    replace: "ğŸ™ŒğŸ¼"
  - trigger: ":smile:"
    replace: "ğŸ˜ƒ"
  - trigger: ":cry:"
    replace: "ğŸ˜¢"
  - trigger: ":think:"
    replace: "ğŸ¤”"

  # Dates
  - trigger: ":date:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell:"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
