"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
(${custom.jj}${custom.git_branch})\
${custom.git_status}\
$cmd_duration\
$line_break\
${custom.nix_shell}\
${custom.sudo}\
$jobs\
$status\
$character"""

command_timeout = 500

# move the rest of the prompt to the right
right_format = """$time"""

[fill]
symbol = ' '

[time]
disabled = false
style = "yellow dimmed"
format = '[$time]($style) '
time_format = "%T"
# utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00 no this nix_shell"

[username]
style_root = "red"
style_user = "purple"
format = "[$user]($style)@"

[hostname]
style = "yellow"
format = "[$hostname]($style) "

[cmd_duration]
format = "[ $duration]($style) "
style = "bold fg:yellow"
min_time = 500

[character]
# alts:  â€ºîª¶ï„…ï”ó°…‚ï‘  ï„
format = "$symbol "
success_symbol = "[â€º](bold green)"
error_symbol = "[â€º](bold red)"
# vicmd_symbol = "[î˜«](bold fg:white,bg:#614b51)"

[jobs]
symbol = "ó°„‰(white dimmed)" # ï˜½ï„…
number_threshold = 1
symbol_threshold = 1
format = "$number$symbol"

# [custom.desk]
# description = "indicates whether you're in a desk-spawned shell"
# command = "(command desk -v &>/dev/null && (desk | grep -q 'No desk activated.' && echo '' || echo 'ğŸš€')) || echo ''"
# when = "true"


[custom.nix_shell]
symbol = "ó±„…"
command = '''
  echo "$(echo $name | sed 's/-shell//')/$IN_NIX_SHELL"
'''
format = '\[[[$symbol](#ffffff) $output](#aaaaaa)\] '
when = "[[ -n $IN_NIX_SHELL ]]"

# [nix_shell]
# impure_msg = '[-impure](#614b51)'
# pure_msg = '[-pure](#888888)'
# unknown_msg = '[-unknown](yellow)'
# format = '[[ó±„…](#ffffff) $name$state](#aaaaaa) '

[custom.sudo]
description = "valid sudo timestamp marker"
command = "echo -n 'ï„¾'"
format = "[$symbol$output]($style) "
style = "bold fg:#614b51"
when = "sudo -vn &>/dev/null"

[custom.jj]
ignore_timeout = true
description = "The current jj status"
detect_folders = [".jj"]
symbol = ""
# symbol = "ó±—† "
# hidden? ğŸ‘»
command = '''
  jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
    separate(" ",
      change_id.shortest(4),
      bookmarks,
      "â‹®",
      concat(
        if(conflict, "ó°”·"),
        if(divergent, "ó°§ˆ"),
        if(hidden, "ó°˜“"),
        if(immutable, "ï„¾"),
      ),
      raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
      raw_escape_sequence("\x1b[1;32m") ++ coalesce(
        truncate_end(29, description.first_line(), "â€¦"),
        "",
      ) ++ raw_escape_sequence("\x1b[0m"),
    )
  '
'''
# "(no description set)",

[git_branch]
disabled = true
truncation_symbol = "â€¦"
truncation_length = 20
symbol = "[ï˜](bold fg:#626262)" # ï¡ï˜
format = "[$branch]($style)"
style = "italic fg:#7c8377"     # 245

[custom.git_branch]
detect_folders = [".git", "!.jj"]
command = "starship module git_branch"
style = "italic fg:#7c8377"            # 245
format = "[$output]($style)"

[git_status]
disabled = true
style = "#7c8377"
format = '([$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind](fg:$style) )'
ahead = " [îª¡](fg:white)"                                                                              # â‡¡
behind = " [îªš](fg:white)"                                                                             # â‡£
diverged = " ó°§ˆîª¡${ahead_count}îªš${behind_count}"
modified = " [ó°›„](fg:purple)"                                                                          #â€¢ï¯‚
# modified = "[~${count}](fg:red)"
staged = " [ï§](fg:green)"
# staged = "[ï§$count](fg:green)"
conflicted = " [ó°”·](bold fg:#FAB005)[ï‘€${count}](fg:#d9bb80)"
stashed = " [ï‚—${count}](fg:white)"
deleted = " [î©¶](fg:red)"
# deleted = "[ï™•$count](fg:red)"
renamed = " [îªœ](fg:white)"
# renamed = "[ï‘š${count}](fg:white)"
untracked = " [ó±˜](fg:#eeeeee)"
# untracked = "[ó±˜${count}](fg:#7c8377)"

[custom.git_status]
detect_folders = [".git", "!.jj"]
command = "starship module git_status"
style = "#7c8377"
format = '[$output](fg:$style)'

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = "bold blue"

# [directory]
# format = "[$path](bold $style)[$read_only]($read_only_style) "
# truncation_length = 2
# style = "fg:blue"
# read_only_style = "fg:red"
# fish_style_pwd_dir_length = 1
# before_repo_root_style = "fg:#555555"
# truncation_symbol = "â€¦/"
# truncate_to_repo = true
# read_only = "  "

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
