# ğŸš€ starship!!

# REF:
# * customs: https://github.com/starship/starship/discussions/1252

format = """
($username\
$hostname)\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[username]
# show_always = true
style_root = "red"
style_user = "purple"
format = "[$user]($style)@"

[hostname]
# ssh_only = false
style = "yellow"
format = "[$hostname]($style) "

[cmd_duration]
format = "[$duration]($style) "

[character]
format = "$symbol "
success_symbol = "[ï”](bold green)"
error_symbol = "[ï”](bold red)"
vicmd_symbol = "[ï”](bold purple)"

[jobs]
symbol = "ï„…"
format = "$symbol"

[custom.desk]
description = "indicates whether you're in a desk-spawned shell"
command = "(command desk -v &>/dev/null && (desk | grep -q 'No desk activated.' && echo '' || echo 'ğŸš€')) || echo ''"
when = "true"

[custom.sudo]
description = "valid sudo timestamp marker"
command = "echo -n 'ï„¾'"
format = "[$symbol$output]($style) "
style = "bold fg:#614b51"
when = "sudo -vn &>/dev/null"

[custom.git_status_dirty]
disabled = true
when = "string length -q -- (git status --porcelain)"
symbol = 'â—‹'
style = 'red bold'
format = '[$symbol]($style) '
shell =["zsh"]

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style) "
style = "bold fg:245"

[git_status]
disabled = false
# # REF:
# # https://github.com/avaaxcx/dotfiles/blob/master/.config/starship.toml
format = '([\[$all_status$ahead_behind\]]($style) )' #(bold fg:#8be9fd)
# format = '([$ahead_behind]($style) )' #(bold fg:#8be9fd)
ahead = "â†‘"
behind = "â†“"
# staged = "â€¢" #â€¢ï¯‚
# modified = "~"
# untracked = "?" #+
deleted = "ï™•" #x
stashed = "ïŸº"
# stashed = "([ïŸº ${count}]))(fg:white)"
# ---
# # REF:
# # https://github.com/fredericrous/dotfiles/blob/main/private_dot_config/starship.toml
# style = "#d8712c"
# format = "(\b$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind(fg:$style))"
# conflicted = "[ï± ](bold fg:88 bg:#d8712c)[ ï‘€ ${count} ](fg:black bg:#d8712c)"
# staged = "[ï§ $count ](fg:black bg:#d8712c)"
# modified = "[ï£ª ${count} ](fg:black bg:#d8712c)"
# renamed = "[ï€« ${count} ](fg:black bg:#d8712c)"
# deleted = "[ï€” ${count} ](fg:black bg:#d8712c)"
# untracked = "[?${count} ](fg:black bg:#d8712c)"
# stashed = "[ï’‡ ${count} ](fg:black bg:#d8712c)"
# ahead = "[ïƒ® ${count} ](fg:#523333 bg:#d8712c)"
# behind = "[ïƒ­ ${count} ](fg:black bg:#d8712c)"
# diverged = "[ï± ](fg:88 bg:#d8712c)[ ï­€ ](fg:black bg:#d8712c)[ïƒ® ${ahead_count} ](fg:black bg:#d8712c)[ïƒ­ ${behind_count} ](fg:black bg:#d8712c)"

[directory]
truncation_length = 10
truncation_symbol = "â€¦/"
truncate_to_repo = false
style = "bold blue"

[aws]
symbol = "îŒ½ "
disabled = true

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"
disabled = true

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "

[swift]
symbol = "ï¯£ "
