lastupdatecheck: 0
recentrepos:
- /Users/seth/code/retriever
- /Users/seth/code/bellhop
- /Users/seth/.dotfiles
- /Users/seth/code/ternreturns
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
