# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
#â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
---
# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # - {trigger: '->', replace: â†’, word: true} # unicode arrow
  # - {trigger: ' mm', replace: ' ğŸ™ˆ'}

  - trigger: '::date'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%m/%d/%Y'

  - trigger: '::isodate'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%Y-%m-%d'

  - trigger: '::time'
    replace: '{{time}}'
    vars:
      - name: time
        type: date
        params:
          format: '%X'

  - trigger: ':flip'
    replace: '(ãƒÂ°Ğ”Â°ï¼‰ãƒï¸µ â”»â”â”»'

  - trigger: '::ip'
    replace: '{{ip}}'
    vars:
      - name: ip
        type: shell
        params:
          cmd: 'curl ifconfig.me'

  - {trigger: '<3', replace: 'ğŸ©¶'} # use grey haeart instead of red one
  - {trigger: ":shrug", replace: "Â¯\\_(ãƒ„)_/Â¯"}
  - trigger: ':wave'
    replace: ğŸ‘‹

  - trigger: ':heart'
    replace: â¤ï¸

  - trigger: ':up'
    replace: ğŸ‘

  - trigger: ':thumb'
    replace: ğŸ‘

  - trigger: ':+1'
    replace: ğŸ‘

  - trigger: ':thumbsup'
    replace: ğŸ‘

  - trigger: ':-1'
    replace: ğŸ‘

  - trigger: ':thumbsdown'
    replace: ğŸ‘

  - trigger: ':flex'
    replace: ğŸ’ª

  - trigger: ':pray'
    replace: ğŸ™

  - trigger: ':rock'
    replace: ğŸ¤˜

  - trigger: ':rofl'
    replace: ğŸ¤£

  - trigger: ':lol'
    replace: ğŸ˜‚

  - trigger: ':poop'
    replace: ğŸ’©

  - trigger: ':100'
    replace: ğŸ’¯

  - trigger: ':eyes'
    replace: ğŸ‘€

  - trigger: ':facepalm'
    replace: ğŸ¤¦

  - trigger: ':hands'
    replace: ğŸ™ŒğŸ¼


  - trigger: ":smile"
    replace: "ğŸ˜ƒ"

  - trigger: ":cry"
    replace: "ğŸ˜¢"

  - trigger: ":hmm"
    replace: "ğŸ¤”"

  - trigger: ":think"
    replace: "ğŸ¤”"

  - trigger: ":yay"
    replace: "ğŸ‰"


  - trigger: "Rene "
    replace: "RenÃ©"
  - trigger: ":rene"
    replace: "RenÃ©"
  # - trigger: ":zoom:"
  #   replace: "https://whereby.com/sethmesser"
  # - trigger: ":meet:"
  #   replace: "https://whereby.com/sethmesser"
  - trigger: ":pop"
    replace: "https://pop.com/j/953-644-320"

  - trigger: ":meet"
    replace: "https://meet.google.com/kry-nbrg-rmy"

  - trigger: ":tm"
    replace: "â„¢"
